export const CountMethodData = {
  'Once Per Event': 'ONCE_PER_EVENT',
  'Once Per Session': 'ONCE_PER_SESSION',
};

export const Currencies = {
  USD: 'United States Dollar',
  EUR: 'Euro',
  JPY: 'Japanese Yen',
  GBP: 'British Pound Sterling',
  AUD: 'Australian Dollar',
  CAD: 'Canadian Dollar',
  CHF: 'Swiss Franc',
  CNY: 'Chinese Yuan',
  SEK: 'Swedish Krona',
  NZD: 'New Zealand Dollar',
  MXN: 'Mexican Peso',
  SGD: 'Singapore Dollar',
  HKD: 'Hong Kong Dollar',
  NOK: 'Norwegian Krone',
  KRW: 'South Korean Won',
  TRY: 'Turkish Lira',
  RUB: 'Russian Ruble',
  INR: 'Indian Rupee',
  BRL: 'Brazilian Real',
  ZAR: 'South African Rand',
  DKK: 'Danish Krone',
  PLN: 'Polish Zloty',
  THB: 'Thai Baht',
  IDR: 'Indonesian Rupiah',
  HUF: 'Hungarian Forint',
  CZK: 'Czech Koruna',
  ILS: 'Israeli New Shekel',
  CLP: 'Chilean Peso',
  PHP: 'Philippine Peso',
  AED: 'United Arab Emirates Dirham',
  COP: 'Colombian Peso',
  PEN: 'Peruvian Sol',
  MYR: 'Malaysian Ringgit',
  SAR: 'Saudi Riyal',
  QAR: 'Qatari Riyal',
  KZT: 'Kazakhstani Tenge',
  VND: 'Vietnamese Dong',
  PKR: 'Pakistani Rupee',
  JOD: 'Jordanian Dinar',
  BGN: 'Bulgarian Lev',
  RON: 'Romanian Leu',
  BHD: 'Bahraini Dinar',
  UAH: 'Ukrainian Hryvnia',
  OMR: 'Omani Rial',
  KWD: 'Kuwaiti Dinar',
  LKR: 'Sri Lankan Rupee',
  NGN: 'Nigerian Naira',
  TWD: 'New Taiwan Dollar',
  IRR: 'Iranian Rial',
  DZD: 'Algerian Dinar',
  ARS: 'Argentine Peso',
  MUR: 'Mauritian Rupee',
  NPR: 'Nepalese Rupee',
  UYU: 'Uruguayan Peso',
  BDT: 'Bangladeshi Taka',
  KES: 'Kenyan Shilling',
  GHS: 'Ghanaian Cedi',
  TZS: 'Tanzanian Shilling',
  PAB: 'Panamanian Balboa',
  ETB: 'Ethiopian Birr',
  CRC: 'Costa Rican Colón',
  GTQ: 'Guatemalan Quetzal',
  HNL: 'Honduran Lempira',
  NIO: 'Nicaraguan Córdoba',
  PYG: 'Paraguayan Guarani',
  UZS: 'Uzbekistani Som',
  AZN: 'Azerbaijani Manat',
  BYN: 'Belarusian Ruble',
  GEL: 'Georgian Lari',
  AMD: 'Armenian Dram',
  MDL: 'Moldovan Leu',
  KGS: 'Kyrgyzstani Som',
  TJS: 'Tajikistani Somoni',
  TMT: 'Turkmenistani Manat',
  MNT: 'Mongolian Tugrik',
  MZN: 'Mozambican Metical',
  AOA: 'Angolan Kwanza',
  BWP: 'Botswanan Pula',
  CDF: 'Congolese Franc',
  MGA: 'Malagasy Ariary',
  MWK: 'Malawian Kwacha',
  ZMW: 'Zambian Kwacha',
  MRO: 'Mauritanian Ouguiya',
  SZL: 'Swazi Lilangeni',
  LSL: 'Lesotho Loti',
  BIF: 'Burundian Franc',
  SLL: 'Sierra Leonean Leone',
  GMD: 'Gambian Dalasi',
  LRD: 'Liberian Dollar',
  SRD: 'Surinamese Dollar',
  XAF: 'CFA Franc BEAC',
  XOF: 'CFA Franc BCEAO',
  XPF: 'CFP Franc',
  FJD: 'Fijian Dollar',
  SBD: 'Solomon Islands Dollar',
  TOP: 'Tongan Paʻanga',
  VUV: 'Vanuatu Vatu',
  WST: 'Samoan Tala',
  KMF: 'Comorian Franc',
  TVD: 'Tuvaluan Dollar',
};
