/* import { openSans } from '@/src/lib/fonts';
 */import '../../styles/globals.css';
import '../../styles/tailwind.css';

/* import { Providers, ReduxProvider } from '../providers'; */
import React from 'react';
/* import Footer from '@/src/components/server/Footer/Footer';
import Navbar from '@/src/components/client/Navbar/Navbar'; */
import Cover from '@/src/components/server/Cover/cover';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(/* {
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children,
}: {
  children: React.ReactNode;
} */) {
  // added suppressHydrationWarning to html tag to prevent hydration mismatch error
  return (
    <>
 {/*      <ReduxProvider>
        <Providers>
          <html
            lang="en"
            suppressHydrationWarning 
            className={`${openSans.className}`}
          >
            <body>
              <Navbar />
              {children}
              <Footer />
            </body>
          </html>
        </Providers>
      </ReduxProvider> */}
      <Cover /> 
    </>
  );
}
