export const variableTypeArray = [
  { type: 'k', name: 'First Party Cookie' },
  { type: 'aev', name: 'Auto-Event Variable' },
  { type: 'c', name: 'Constant' },
  { type: 'jsm', name: 'Custom JS' },
  { type: 'v', name: 'Data Layer Variable' },
  { type: 'd', name: 'DOM Element' },
  { type: 'f', name: 'HTTP Referrer' },
  { type: 'j', name: 'JavaScript Variable' },
  { type: 'gas', name: 'Google Analytics Settings Variable' },
  { type: 'smm', name: 'Lookup Table' },
  { type: 'remm', name: 'Regex Lookup Table' },
  { type: 'u', name: 'URL' },
  { type: 'vis', name: 'Element Visibility' },
  { type: 'e', name: 'Custom Event' },
  { type: 'ev', name: 'Environment Name' },
  { type: 'r', name: 'Random Number' },
  { type: 'uv', name: 'Undefined Value' },
  { type: 'awec', name: 'User Provided Data' },
  { type: 'cid', name: 'Container Id' },
  { type: 'dbg', name: 'Debug' },
  { type: 'gtes', name: 'Google Tag: Event Settings' },
  { type: 'gtcs', name: 'Google Tag: Configuration Settings' },
  { type: 'ctv', name: 'Container Version Number' },
];

export const httpReferrerType = [
  { type: 'fullReferrer', name: 'Full Referrer' },
  { type: 'protocol', name: 'Protocol' },
  { type: 'hostName', name: 'Host Name' },
  { type: 'port', name: 'Port' },
  { type: 'path', name: 'Path' },
  { type: 'query', name: 'Query' },
  { type: 'fragment', name: 'Fragment' },
];
