name: Supa-backup

on:
  push:
    branches:
      - main
      - sandbox
  pull_request:
    branches:
      - main
      - sandbox
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  run_db_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      supabase_db_url_prod: ${{ secrets.SUPABASE_DB_URL_OPTIMAFLO_PROD }} # Production DB URL
      supabase_db_url_sandbox: ${{ secrets.SUPABASE_DB_URL_OPTIMAFLO_SANDBOX }} # Sandbox DB URL
    steps:
      - uses: actions/checkout@v4 # Ensure to use the latest version compatible with Node 16/20
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Set DB URL
        run: echo "supabase_db_url=${{ github.ref == 'refs/heads/sandbox' && env.supabase_db_url_sandbox || env.supabase_db_url_prod }}" >> $GITHUB_ENV
      - name: Backup roles
        run: supabase db dump --db-url "$supabase_db_url" -f roles.sql --role-only
      - name: Backup schema
        run: supabase db dump --db-url "$supabase_db_url" -f schema.sql
      - name: Backup data
        run: supabase db dump --db-url "$supabase_db_url" -f data.sql --data-only --use-copy
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Fetch and Checkout Branch
        run: |
          git fetch origin
          git branch -a  # List all branches for debugging
          if git show-ref --quiet refs/heads/backup-${{ github.ref == 'refs/heads/sandbox' && 'sandbox' || 'main' }}-branch; then
            git checkout backup-${{ github.ref == 'refs/heads/sandbox' && 'sandbox' || 'main' }}-branch
          else
            git checkout -b backup-${{ github.ref == 'refs/heads/sandbox' && 'sandbox' || 'main' }}-branch
          fi
      - name: Commit files
        run: |
          git add roles.sql schema.sql data.sql
          git commit -m "Supabase backup for ${{ github.ref == 'refs/heads/sandbox' && 'sandbox' || 'main' }}"
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4 # Update to the latest version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Supabase backup for ${{ github.ref == 'refs/heads/sandbox' && 'sandbox' || 'main' }}
          branch: backup-${{ github.ref == 'refs/heads/sandbox' && 'sandbox' || 'main' }}-branch
          title: "[AUTO] Supabase backup for ${{ github.ref == 'refs/heads/sandbox' && 'sandbox' || 'main' }}"
          body: "Automated backup of Supabase data for ${{ github.ref == 'refs/heads/sandbox' && 'sandbox' || 'main' }}"
          base: ${{ github.ref == 'refs/heads/sandbox' && 'sandbox' || 'main' }}
      - name: Verify Pull Request Creation
        if: steps.create_pr.outputs.pull-request-url != ''
        run: |
          echo "Pull request created: ${{ steps.create_pr.outputs.pull-request-url }}"
