/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SramKB6TCO7
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "src/components/ui/select"
import { Button } from "src/components/ui/button"

export function audience-form() {
  return (
    <div className="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow">
      <div className="flex items-center mb-4">
        <CircleIcon className="text-[#1e90ff] mr-2" />
        <h2 className="text-lg font-semibold">Include users when:</h2>
      </div>
      <div className="space-y-4">
        <div className="flex items-center justify-between p-4 bg-gray-100 rounded">
          <Select>
            <SelectTrigger id="condition1">
              <SelectValue placeholder="Add new condition" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="option1">Option 1</SelectItem>
              <SelectItem value="option2">Option 2</SelectItem>
            </SelectContent>
          </Select>
          <div className="flex items-center space-x-2">
            <Button className="text-blue-500" variant="ghost">
              Or
            </Button>
            <XIcon className="text-gray-400" />
          </div>
        </div>
        <div className="flex items-center justify-between p-4 bg-gray-100 rounded">
          <Select>
            <SelectTrigger id="condition2">
              <SelectValue placeholder="Add new condition" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="option1">Option 1</SelectItem>
              <SelectItem value="option2">Option 2</SelectItem>
            </SelectContent>
          </Select>
          <div className="flex items-center space-x-2">
            <Button className="text-blue-500" variant="ghost">
              Or
            </Button>
            <XIcon className="text-gray-400" />
          </div>
        </div>
        <div className="border-t border-dashed" />
        <div className="flex items-center justify-between p-4 bg-gray-100 rounded">
          <Select>
            <SelectTrigger id="condition3">
              <SelectValue placeholder="Add new condition" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="option1">Option 1</SelectItem>
              <SelectItem value="option2">Option 2</SelectItem>
            </SelectContent>
          </Select>
          <div className="flex items-center space-x-2">
            <Button className="text-blue-500" variant="ghost">
              And
            </Button>
            <XIcon className="text-gray-400" />
          </div>
        </div>
      </div>
      <div className="flex items-center justify-between mt-6">
        <Button className="flex items-center space-x-2" variant="secondary">
          <PlusIcon className="text-white" />
          <span>Add condition group to include</span>
        </Button>
        <Button className="flex items-center space-x-2" variant="secondary">
          <BarChartIcon className="text-white" />
          <span>Add sequence to include</span>
        </Button>
      </div>
    </div>
  )
}


function CircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function BarChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}
